import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import ChatBox from '../../../components/chat-box';
import ChatList from '../../../components/chat-list';
import Header from '../../../components/layout/Header';
import useChatList from '../../../hooks/use-chat-list';

const Chat = () => {
  
  
  return (
    <>
      <Head>
        <title>Goodjobs-Chatting</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-screen'>
        <Header />

        <div className='flex h-4/5'>
          <div className='basis-1/3'>
            <ChatList />
          </div>

          <div className='basis-2/3'>
            <ChatBox />
          </div>
        </div>
      </main>
    </>
  );
};

export default Chat;
