import Head from 'next/head';
import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Goodjobs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />

        <Footer />
      </main>
    </div>
  );
}
