import Head from 'next/head';
import { useRouter } from 'next/router';
import ChatBox from '../components/chat';
import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';
import useFirebaseAuth from '../hooks/use-auth';

export default function Home() {
  const auth = useFirebaseAuth();
  const router = useRouter();

  const { authUser, logout } = auth;
  
  return (
    <div>
      <Head>
        <title>Goodjobs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <div className='h-screen'>
          {authUser ? (
            <>
              <button onClick={logout}>Logout</button>
              <ChatBox />
            </>
          ) : (
            <button onClick={() => router.push('/login')}>Login</button>
          )}
        </div>
        <Footer />
      </main>
    </div>
  );
}
